### ISSUE TITLE
Unrecognized option "form" under "twig"

### ISSUE THREAD

**Issue by xiranst** [Padam87/AttributeBundle#38]
according the installation steps, i got this error message after clear the cache.
ps: i didn't add the jms_di_extra configuration in config.yml

how to do now?

**Comment by Padam87** [comment]
This is due to a change in the twig bundle.
This bundle should be updated, but I cannot handle it alone, because my current projects don't use this.
As a quick fix, instead of importing the bundle's config.yml, you can do this:

```yaml
twig:
    form_themes:
        - 'Padam87AttributeBundle:Form:attributeCollection.html.twig'
```
